import { View, Text, ScrollView, Pressable } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import Ionicons from "@react-native-vector-icons/ionicons";

import { useTheme, makeStyles, spacing, radius, fonts, fontSize } from "@/src/theme";

function Row({
  icon,
  label,
  value,
  onPress,
  testID,
}: {
  icon: any;
  label: string;
  value?: string;
  onPress?: () => void;
  testID?: string;
}) {
  const styles = useStyles();
  const { colors } = useTheme();
  return (
    <Pressable style={styles.row} onPress={onPress} disabled={!onPress} testID={testID}>
      <Ionicons name={icon} size={20} color={colors.brandPrimary} />
      <Text style={styles.rowLabel}>{label}</Text>
      {value ? <Text style={styles.rowValue}>{value}</Text> : null}
      {onPress ? <Ionicons name="chevron-forward" size={18} color={colors.muted} /> : null}
    </Pressable>
  );
}

export default function About() {
  const styles = useStyles();
  const { colors } = useTheme();
  const insets = useSafeAreaInsets();

  return (
    <View style={styles.root}>
      <View style={[styles.header, { paddingTop: insets.top + spacing.md }]}>
        <Text style={styles.title}>About</Text>
      </View>

      <ScrollView
        contentContainerStyle={{ paddingHorizontal: spacing.xl, paddingBottom: 120 }}
        showsVerticalScrollIndicator={false}
      >
        <View style={styles.logoWrap}>
          <View style={styles.logo}>
            <Ionicons name="medkit" size={30} color={colors.onBrandPrimary} />
          </View>
          <Text style={styles.appName}>AI Dermatologist</Text>
          <Text style={styles.tagline}>AI-Powered Skin Lesion Analysis</Text>
        </View>

        <Text style={styles.paragraph}>
          AI Dermatologist provides a preliminary analysis of skin lesions using advanced artificial intelligence.
          Upload a photo to receive an AI-powered assessment identifying potential conditions.
        </Text>

        <View style={styles.privacy} testID="about-privacy">
          <View style={styles.disclaimerHead}>
            <Ionicons name="lock-closed" size={18} color={colors.brandPrimary} />
            <Text style={styles.disclaimerTitle}>Your data stays on this phone</Text>
          </View>
          <Text style={styles.disclaimerText}>
            Your account, scan history, notes and reports are stored only on this device — there is no cloud
            account and no server. Photos are sent to the AI model for the moment of analysis only, and an
            internet connection is needed for that step alone.
          </Text>
        </View>

        <View style={styles.disclaimer} testID="about-disclaimer">
          <View style={styles.disclaimerHead}>
            <Ionicons name="warning" size={18} color={colors.warning} />
            <Text style={styles.disclaimerTitle}>Not Medical Advice</Text>
          </View>
          <Text style={styles.disclaimerText}>
            This application is for informational and educational purposes only. The analysis is generated by an AI
            and is not a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice
            of your physician or qualified health provider.
          </Text>
        </View>

        <Text style={styles.groupLabel}>Information</Text>
        <View style={styles.group}>
          <Row icon="person-outline" label="Developed by" value="aivicventures" />
          <View style={styles.divider} />
          <Row icon="information-circle-outline" label="Version" value="1.0.9" />
        </View>

        <Text style={styles.footer}>Powered by Google Gemini</Text>
      </ScrollView>
    </View>
  );
}

const useStyles = makeStyles((colors) => ({
  root: { flex: 1, backgroundColor: colors.surface },
  header: { paddingHorizontal: spacing.xl, paddingBottom: spacing.md },
  title: { fontFamily: fonts.display, fontSize: fontSize["2xl"], color: colors.onSurface },
  logoWrap: { alignItems: "center", marginTop: spacing.md, marginBottom: spacing.xl },
  logo: {
    width: 72,
    height: 72,
    borderRadius: radius.lg,
    backgroundColor: colors.brandPrimary,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: spacing.md,
  },
  appName: { fontFamily: fonts.display, fontSize: fontSize.xl, color: colors.onSurface },
  tagline: { fontFamily: fonts.body, fontSize: fontSize.base, color: colors.muted, marginTop: 2 },
  paragraph: {
    fontFamily: fonts.body,
    fontSize: fontSize.base,
    color: colors.onSurfaceSecondary,
    lineHeight: 21,
    marginBottom: spacing.xl,
  },
  disclaimer: {
    backgroundColor: colors.surfaceTertiary,
    borderRadius: radius.lg,
    borderLeftWidth: 4,
    borderLeftColor: colors.warning,
    padding: spacing.lg,
    marginBottom: spacing.xl,
  },
  privacy: {
    backgroundColor: colors.surfaceTertiary,
    borderRadius: radius.lg,
    borderLeftWidth: 4,
    borderLeftColor: colors.brandPrimary,
    padding: spacing.lg,
    marginBottom: spacing.xl,
  },
  disclaimerHead: { flexDirection: "row", alignItems: "center", gap: spacing.sm, marginBottom: spacing.sm },
  disclaimerTitle: { fontFamily: fonts.bodySemi, fontSize: fontSize.lg, color: colors.onSurface },
  disclaimerText: { fontFamily: fonts.body, fontSize: fontSize.base, color: colors.muted, lineHeight: 20 },
  groupLabel: {
    fontFamily: fonts.bodyMedium,
    fontSize: fontSize.sm,
    color: colors.muted,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: spacing.sm,
  },
  group: {
    backgroundColor: colors.surfaceSecondary,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: spacing.xl,
    overflow: "hidden",
  },
  row: { flexDirection: "row", alignItems: "center", gap: spacing.md, padding: spacing.lg },
  rowLabel: { fontFamily: fonts.bodyMedium, fontSize: fontSize.lg, color: colors.onSurface, flex: 1 },
  rowValue: { fontFamily: fonts.mono, fontSize: fontSize.base, color: colors.muted },
  divider: { height: 1, backgroundColor: colors.divider, marginLeft: spacing.lg },
  footer: { textAlign: "center", fontFamily: fonts.body, fontSize: fontSize.sm, color: colors.muted },
}));
